### ISSUE TITLE
validateIf based on other fields

### ISSUE THREAD

**Issue by joshua1** [Alexandre-Fernandez/svelidate#4]
Hi , I came upon this lib and find it interesting. I want to suggest that either validateIf be extended to take other fields in the form into consideration or introduce a validateWhen , which validates , when conditions based on other fields in the form are met

**Comment by Alexandre-Fernandez** [comment]
Hi @joshua1, thanks for using svelidate.

> validateIf should take other fields in the form into consideration

I think I didn't update the documentation but this may be already implemented.
You should be getting the `form` as the second parameter `validateIf((fieldValue, form) => form.field.value.length > 1)`, can you please try it ? I'll update the doc afterwards.

> introduce a validateWhen , which validates , when conditions based on other fields in the form are met

Isn't that the same as your first suggestion ?

**Comment by Alexandre-Fernandez** [comment]
Hi @joshua1, thanks for using svelidate.

"validateIf should take other fields in the form into consideration"
I think I didn't update the documentation but this may be already implemented.
You should be getting the `form` as the second parameter `validateIf((fieldValue, form) => true)`, can you please try it ? I'll update the doc afterwards.

"introduce a validateWhen , which validates , when conditions based on other fields in the form are met"
Isn't that the same as your first suggestion ?

**Comment by joshua1** [comment]
@Alexandre-Fernandez  I will give it a try and close this . Thanks @Alexandre-Fernandez
